# Stage 1: Build
FROM node:20-alpine AS builder

WORKDIR /app
 
COPY package*.json ./
 
RUN npm install --omit=dev

COPY . .

FROM gcr.io/distroless/nodejs20-debian13

WORKDIR /app

COPY --from=builder /app /app

EXPOSE 5004

ENV NODE_ENV=production

CMD ["server.js"]