services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - ecommerce-nt

  auth-service:
    container_name: auth-service
    environment: 
      MONGO_URI: mongodb://admin:admin123@mongodb:27017/ecommerce?authSource=admin
      PORT: 5001
    build:
      context: ./backend/auth-service 
      dockerfile: Dockerfile-slim
    
    networks:
      - ecommerce-nt
    ports:
      - 5001:5001
    depends_on:
      - mongodb
  user-service:
    container_name: user-service
    environment: 
      MONGO_URI: mongodb://admin:admin123@mongodb:27017/ecommerce?authSource=admin
      PORT: 5002
    build:
      context: ./backend/user-service 
      dockerfile: Dockerfile-slim
    networks:
      - ecommerce-nt
    ports:
      - 5002:5002
    depends_on:
       - mongodb
  product-service:
    container_name: product-service
    environment: 
      MONGO_URI: mongodb://admin:admin123@mongodb:27017/ecommerce?authSource=admin
      PORT: 5003
    build:
      context: ./backend/product-service 
      dockerfile: Dockerfile-slim
    networks:
      - ecommerce-nt
    ports:
      - 5003:5003
    depends_on:
      - mongodb
  cart-service:
    container_name: cart-service
    build:
      context: ./backend/cart-service 
      dockerfile: Dockerfile-slim
    networks:
      - ecommerce-nt
    ports:
      - 5004:5004
    depends_on:
      - mongodb
  order-service:
    container_name: order-service
    environment: 
      MONGO_URI: mongodb://admin:admin123@mongodb:27017/ecommerce?authSource=admin
      PORT: 5005
    build:
      context: ./backend/order-service 
      dockerfile: Dockerfile-slim
    networks:
      - ecommerce-nt
    ports:
      - 5005:5005
    depends_on:
      - mongodb

  api-gateway:
    container_name: api-gateway
    build:
      context: ./backend/api-gateway 
      dockerfile: Dockerfile-slim
    environment:
        AUTH_SERVICE_URL: http://auth-service:5001/auth
        USER_SERVICE_URL: http://user-service:5002/
        PRODUCT_SERVICE_URL: http://product-service:5003/
        CART_SERVICE_URL: http://cart-service:5004/
        ORDER_SERVICE_URL: http://order-service:5005/
        PORT: 5000
    networks:
      - ecommerce-nt
    ports:
      - 5000:5000
    depends_on:
      - mongodb
      - product-service
      - user-service
      - auth-service
      - order-service
      - cart-service
networks:
  ecommerce-nt:
    driver: bridge
volumes:
  mongo-data: