# Stage 1: Build
FROM node:24.14.0-alpine3.23 AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci --omit=dev

COPY . .

# Stage 2: Runtime
FROM gcr.io/distroless/nodejs24-debian13:nonroot

WORKDIR /app

COPY --from=builder /app /app

EXPOSE 5000

ENV NODE_ENV=production

CMD ["server.js"]