# Stage 1: Build
FROM node:24.14.0-alpine AS builder

WORKDIR /app
 
COPY package*.json ./
 
RUN npm install --omit=dev

COPY . .

FROM gcr.io/distroless/nodejs24-debian12

WORKDIR /app

COPY --from=builder /app /app

EXPOSE 5000

ENV NODE_ENV=production

CMD ["server.js"]