# Stage 1: Build
FROM node:22.22.1-alpine3.23 AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
# Stage 2: Runtime
FROM gcr.io/distroless/nodejs22-debian13:nonroot
WORKDIR /app
COPY --from=builder /app /app
EXPOSE 5000
ENV NODE_ENV=production
CMD ["server.js"]