name: Check Lint
on:
    workflow_call:
        inputs:
            service-path:
                required: true
                type: string

jobs:
    linter:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
        
            - name: Setup Node.Js
              uses: actions/setup-node@v4
              with:
                node-version: 20
                cache: 'npm' 
                directory: ${{ inputs.service-path }}

            - name: debug path
              run: echo  ${{ inputs.service-path }}
               

            # - name: Install dependecy
            #   run: npm ci
            #   working-directory: ${{ inputs.service-path }}

            # - name: Run ESLint
            #   run: npx eslint . --ext .js,.jsx,.ts,.tsx
            #   working-directory: ${{ inputs.service-path }} 