name: Check Lint
on:
    workflow_call:
        inputs:
            service-path:
                required: true
                type: string

jobs:
    linter:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
        
            - name: Setup Node.Js
              uses: actions/setup-node@v6
              with:
                node-version: '24' 

            - name: Cache node_modules for service
              uses: actions/cache@v3
              with:
                path: ${{ github.workspace }}/${{ inputs.service-path }}/node_modules
                key: ${{ runner.os }}-node-${{ hashFiles('${{ github.workspace }}/${{ inputs.service-path }}/package-lock.json') }}
                restore-keys: |
                    ${{ runner.os }}-node-  

             
            - name: Install dependecy
              run: npm install
              working-directory: ${{ github.workspace }}/${{ inputs.service-path }}

            # - name: Run ESLint
            #   run: npx eslint . --ext .js,.jsx,.ts,.tsx
            #   working-directory: ${{ github.workspace }}/${{ inputs.service-path }} 