name: End to End DevSecOps Pipeline

on:
  push:
    branches: [dev]

jobs: 
  check-code:
    uses: ./.github/workflows/check-code-linter.yml
    strategy:
      matrix:
        service-path:
          - backend/auth-service
          - backend/user-service
          - backend/product-service
          - backend/cart-service
          - backend/order-service
          - backend/api-gateway
        #   - frontend/client-app
    with:
      service-path: ${{ matrix.service-path }}
    secrets: inherit
 