name: Dockerfile scan

on:
    workflow_call:
        inputs:
            service-path:
                required: true
                type: string

jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
            - name: code checkout
              uses: actions/checkout@v4

            - name: Dockerfile validate
              uses: hadolint/hadolint-action@v3.3.0
              with:
                  dockerfile: ${{ inputs.service-path }}/Dockerfile-slim 
